ci:
  autofix_prs: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff-format
        args: ["--diff", "src", "tests"]
      - id: ruff
        args: ["src", "tests"]
