site_name: Betterproto2
site_url: https://betterproto.github.io/python-betterproto2/
theme:
  name: material
  palette:
    primary: deep orange
    accent: deep orange
  
  features:
   - navigation.tabs

nav:
  - Betterproto2: 
     - index.md
     - Quick start: quick-start.md
     - Tutorial:
        - Messages: tutorial/messages.md
     - API: api.md
     - Migrating: migrating.md
  - Betterproto2 compiler: https://betterproto.github.io/python-betterproto2-compiler/

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences