name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  code-quality:
    name: Check code/doc formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.5"
        python-version: "3.10"

    - name: Install betterproto2
      working-directory: ./betterproto2
      run: uv sync --locked --all-extras --all-groups

    - name: Install betterproto2_compiler
      working-directory: ./betterproto2_compiler
      run: uv sync --locked --all-extras --all-groups

    - name: Pyright
      working-directory: ./betterproto2
      shell: bash
      run: uv run poe typecheck

    - name: Pyright
      working-directory: ./betterproto2_compiler
      shell: bash
      run: uv run poe typecheck
