name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  code-quality:
    name: Check code formatting and typechecking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.11.11"
        python-version: "3.10"

    - name: Install workspace
      run: uv sync --locked --all-extras --all-groups

    - name: Check formatting and linting (betterproto2)
      run: uv run poe check-lib

    - name: Check formatting and linting (betterproto2_compiler)
      run: uv run poe check-plugin

    - name: Check proto formatting
      run: uv run poe check-proto-plugin

    - name: Pyright (betterproto2)
      run: uv run poe typecheck-lib

    - name: Pyright (betterproto2_compiler)
      run: uv run poe typecheck-plugin
