name: documentation
on:
  release:
    types:
      - published
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
          python-version: "3.10"

      - name: Install betterproto2
        working-directory: ./betterproto2
        run: uv sync --locked --all-extras --all-groups

      - name: Build and deploy documentation
        working-directory: ./betterproto2
        run: uv run mkdocs gh-deploy --force